homework v1
dgshulgin/go-first-floor-sprint-five pull request #1
Opened 2023-12-31 08:34 UTC by dgshulgin

2023-12-31 09:54 UTC, robotomize requested changes
Отличная работа, но нужно кое-что поправить

2023-12-31 09:54 UTC, robotomize commented on main.go
> +	return s.Training.TrainingInfo()
В данном случае скорость рассчитывается из встроенной структуры Training, а должна расчитываться скорость плавания. Попробуйте явно вернуть InfoMessage и подставить нужные значения

2023-12-31 09:54 UTC, robotomize commented on main.go
> +	calories := subFormula * r.Weight / MInKm * r.Duration.Hours() * MinInHours
Отлично разбили на предпосчитаные выражения

2023-12-31 09:54 UTC, robotomize commented on main.go
> +	subFormulaWeight := CaloriesWeightMultiplier * w.Weight
Тут также хорошо сделано, удобно просматривать

2023-12-31 09:54 UTC, robotomize commented on main.go
> +	return float64(s.LengthPool) * float64(s.CountPool) / MInKm / s.Duration.Hours()
Нужно добавить проверку, что s.Duration больше 0. Так как имеем дело с делением

2023-12-31 09:54 UTC, robotomize commented on main.go
> -	...
Нужно добавить проверку, что s.Duration больше 0. Так как имеем дело с делением

2023-12-31 13:34 UTC, dgshulgin commented on main.go
> +	return s.Training.TrainingInfo()
fixed

2023-12-31 13:34 UTC, dgshulgin commented on main.go
> -	...
fixed

2023-12-31 13:37 UTC, dgshulgin commented on main.go
> +	return float64(s.LengthPool) * float64(s.CountPool) / MInKm / s.Duration.Hours()
fixed

2024-01-01 06:02 UTC, robotomize approved these changes
Отличная работа Дмитрий, с Новым Годом!=)

2024-01-04 10:31 UTC, merged